model:
  name: resnet18
  num_classes: 10

task:
  name: kinetics_demo
  finished:
    max_steps: 100_000
  dataloader:
    train:
      batch_size: 16

optimizer:
  name: adamw

lr_scheduler:
  name: linear

trainer:
  name: ddp

logger:
  - name: stdout
  - name: tensorboard
