name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
      - name: Build package
        run: python -m build --wheel --outdir dist/ .
      - uses: actions/upload-artifact@v3
        with:
          name: wheel-${{ matrix.os }}-${{ github.sha }}
          path: dist/*.whl

  build-sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build --sdist --outdir dist/ .
      - uses: actions/upload-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/*.tar.gz

  upload-wheel:
    name: Upload wheel
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    steps:
      - name: Download Ubuntu wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel-ubuntu-latest-${{ github.sha }}
          path: dist/
      - name: Download MacOS wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel-macos-latest-${{ github.sha }}
          path: dist/
      - name: Download sdist
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - name: Build and publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
