name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            build \
            wheel \
            cmake \
            mypy \
            pybind11 \
            torch \
            --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Build package
        run: python -m build --no-isolation --sdist --outdir dist/ .
      - name: Build and publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
